CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR (11)
);

CREATE TABLE PET (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    RACA VARCHAR(100),
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID)
);

